name: cookly
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  dot_navigation_bar: ^1.0.2
  easy_localization: ^3.0.3
  fancy_shimmer_image: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: null
  google_fonts: ^6.1.0
  intl: any
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  supabase_flutter: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.8
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - assets/illustrations/
    - .env
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/english/DMSans-Bold.ttf
        - asset: assets/fonts/english/DMSans-Black.ttf
        - asset: assets/fonts/english/DMSans-ExtraBold.ttf
        - asset: assets/fonts/english/DMSans-ExtraLight.ttf
        - asset: assets/fonts/english/DMSans-Light.ttf
        - asset: assets/fonts/english/DMSans-Medium.ttf
        - asset: assets/fonts/english/DMSans-Regular.ttf
        - asset: assets/fonts/english/DMSans-SemiBold.ttf
        - asset: assets/fonts/english/DMSans-Thin.ttf
